# Generated by Django 4.2.30 on 2026-08-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='consultation_type',
            field=models.CharField(default='Initial Strategy Consultation', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='meeting_platform',
            field=models.CharField(default='Google Meet', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
