# Generated by Django 4.2.30 on 2026-09-01 01:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20260824_1151'),
        ('bookings', '0003_booking_consultation_type_booking_meeting_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_time', models.DateTimeField()),
                ('consultation_type', models.CharField(default='Initial Strategy Consultation', max_length=100)),
                ('meeting_platform', models.CharField(default='Google Meet', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='available_slots', to='users.brokerprofile')),
            ],
            options={
                'db_table': 'available_slots',
                'ordering': ['slot_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='availableslot',
            constraint=models.UniqueConstraint(fields=('broker', 'slot_time'), name='unique_broker_available_slot_time'),
        ),
    ]
