# Generated by Django 4.2.30 on 2026-08-24 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_center', '0001_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='loans.loanapplication'),
        ),
    ]
