# Generated by Django 4.2.30 on 2026-09-23 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('loan_status', 'Loan status'), ('communication', 'Communication'), ('mfa', 'MFA'), ('system', 'System')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_object_type', models.CharField(blank=True, max_length=100)),
                ('related_object_id', models.CharField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_2c3905_idx'), models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_4b40ec_idx')],
            },
        ),
    ]
