# Generated by Django 4.2.30 on 2026-09-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20260824_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('broker', 'Broker'), ('loan_processing', 'Loan Processing')], max_length=20),
        ),
    ]
