# Generated by Django 4.2.30 on 2026-09-07 13:22

from django.db import migrations


def fix_compliance_role(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(role="COMPLIANCE").update(
        role="loan_processing",
        status="active",
    )

class Migration(migrations.Migration):
    dependencies = [
    ("users", "0003_alter_user_role"),
    ]
    operations = [
     migrations.RunPython(fix_compliance_role, migrations.RunPython.noop),
    ]