# Generated by Django 4.2.30 on 2026-09-09 00:00

from django.db import migrations


def update_broker_roles(apps, schema_editor):
    # Phase 1 legacy: this migration previously collapsed broker->loan_processing.
    # Fixed 2026-09-10: now a no-op to preserve broker role. Existing brokers already migrated
    # are kept; use shell to re-create broker@bai.finance if needed. See rotation-note.
    # Kept as RunPython.noop for backwards compatibility on fresh DBs where 0001 already has loan_processing choice.
    pass


def reverse_broker_roles(apps, schema_editor):
    # Safe reverse: do nothing (previously corrupted loan_processing -> broker)
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_fix_compliance_to_loan_processing'),
    ]

    operations = [
        migrations.RunPython(update_broker_roles, reverse_code=reverse_broker_roles),
    ]