# Generated by Django 4.2.30 on 2026-09-09 00:00

from django.db import migrations


def update_broker_roles(apps, schema_editor):
    # Adjust 'auth' or 'users' depending on where your User model lives
    # If using default User: apps.get_model('auth', 'User')
    # If using custom User: apps.get_model('users', 'User')
    User = apps.get_model('users', 'User')
    
    User.objects.filter(role='broker').update(role='loan_processing')


def reverse_broker_roles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(role='loan_processing').update(role='broker')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_fix_compliance_to_loan_processing'),
    ]

    operations = [
        migrations.RunPython(update_broker_roles, reverse_code=reverse_broker_roles),
    ]