# Generated by Django 4.2.30 on 2026-08-24 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='invitation',
            name='invitations_status_9e1071_idx',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(help_text='Expiration date and time for security.'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Primary key. Unique identifier.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='sent_by',
            field=models.ForeignKey(blank=True, db_column='sent_by', help_text='Admin or user who generated/sent the invitation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', help_text='Current state of the invitation link.', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(editable=False, help_text='Unique, secure token embedded in the email link.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='user',
            field=models.ForeignKey(db_column='user_id', help_text='Target user account associated with the invitation.', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
