# Generated by Django 4.2.30 on 2026-08-24 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to='users.brokerprofile'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='users.clientprofile'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['client', 'status'], name='loan_applic_client__7e2fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['broker', 'status'], name='loan_applic_broker__d46174_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['created_at'], name='loan_applic_created_15dc53_idx'),
        ),
    ]
